apiVersion: v1
kind: Service
metadata:
  name: {{ include "sfir.fullname" . }}-api
  labels:
    {{- include "sfir.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      name: http
  selector:
    app.kubernetes.io/component: api
