from enum import StrEnum


class SyncJobStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PAUSED = "paused"


class SyncType(StrEnum):
    FULL = "full"
    INCREMENTAL = "incremental"
    SCHEDULED = "scheduled"
    MANUAL = "manual"
    FORCE = "force"
    RECOVERY = "recovery"
    PARTIAL = "partial"
    METADATA_TYPE = "metadata_type"


class MetadataAction(StrEnum):
    ADDED = "added"
    CREATED = "created"
    UPDATED = "updated"
    DELETED = "deleted"


class RetryStatus(StrEnum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    EXHAUSTED = "exhausted"


class BatchStatus(StrEnum):
    COMPLETED = "completed"
    FAILED = "failed"


class ConflictResolution(StrEnum):
    KEEP_EXISTING = "keep_existing"
    OVERWRITE = "overwrite"
    SKIP = "skip"
    MANUAL = "manual"


KNOWN_METADATA_TYPES: list[str] = [
    "Account",
    "ApexClass",
    "ApexPage",
    "ApexTrigger",
    "ApexComponent",
    "ApprovalProcess",
    "AssignmentRules",
    "AutoResponseRules",
    "Campaign",
    "Case",
    "CaseSubjectParticle",
    "Certificate",
    "ChatterExtension",
    "Claim",
    "ClassificationExample",
    "CleanDataService",
    "Community",
    "CommunityTemplateDefinition",
    "CompactLayout",
    "ConnectedApp",
    "Contact",
    "ContentAsset",
    "CorsWhitelistOrigin",
    "CspTrustedSite",
    "CustomApplication",
    "CustomBadge",
    "CustomComponent",
    "CustomHelpMenuItem",
    "CustomHelpMenuSection",
    "CustomLabel",
    "CustomLabels",
    "CustomMetadata",
    "CustomNotificationType",
    "CustomObject",
    "CustomObjectTranslation",
    "CustomPageWebLink",
    "CustomPermission",
    "CustomSite",
    "CustomTab",
    "CustomValue",
    "Dashboard",
    "DashboardFolder",
    "DataCategoryGroup",
    "DataImport",
    "DelegateGroup",
    "Document",
    "DocumentChecklist",
    "DuplicateRule",
    "EmailServicesFunction",
    "EmailTemplate",
    "EmbeddedServiceBranding",
    "EmbeddedServiceConfig",
    "EmbeddedServiceMenuSettings",
    "EscalationRules",
    "Event",
    "EventDelivery",
    "EventSubscription",
    "ExternalDataSource",
    "ExternalServiceRegistration",
    "FieldRestrictionRule",
    "FieldSet",
    "FieldServiceMobileSettings",
    "FlexiPage",
    "Flow",
    "FlowCategory",
    "FlowDefinition",
    "FlowTest",
    "Folder",
    "Form",
    "FormulaField",
    "GlobalPicklist",
    "GlobalValueSet",
    "Group",
    "GroupType",
    "HomePageComponent",
    "HomePageLayout",
    "InboundCertificate",
    "Index",
    "InsightType",
    "IntegrationConsumptionPolicy",
    "Interaction",
    "Invoice",
    "Item",
    "Knowledge",
    "Language",
    "Layout",
    "Lead",
    "Letterhead",
    "LightningBolt",
    "LightningComponentBundle",
    "LightningExperienceTheme",
    "LightningMessageChannel",
    "LightningOnboardingConfig",
    "ListView",
    "LiveAgentSettings",
    "LiveChatButton",
    "LiveChatDeployment",
    "LiveChatSensitiveDataRule",
    "Macro",
    "MatchingRule",
    "Metadata",
    "MilestoneType",
    "MlDomain",
    "MobileApplicationDetail",
    "ModerationRule",
    "MyDomainDiscoverableLogin",
    "NamedCredential",
    "NavigationMenu",
    "Network",
    "NotificationTypeConfig",
    "OauthCustomScope",
    "OauthTokenExchangeHandler",
    "ObjectHierarchy",
    "Opportunity",
    "OpportunityLineItem",
    "Order",
    "OrderItem",
    "OrgPreference",
    "OutboundNetworkConnection",
    "PathAssistant",
    "Payment",
    "PaymentGateway",
    "PaymentMethod",
    "PermissionSet",
    "PermissionSetGroup",
    "PersonAccountOwner",
    "Picklist",
    "Portal",
    "PostTemplate",
    "Prediction",
    "PresenceConfig",
    "Pricebook",
    "Pricebook2",
    "PricingProfile",
    "Process",
    "Product",
    "Product2",
    "Profile",
    "ProfilePasswordPolicy",
    "ProfileSessionSetting",
    "Prompt",
    "PromptRule",
    "Queue",
    "QuickAction",
    "Quote",
    "Recommendation",
    "RecordActionDeployment",
    "RecordType",
    "RedirectWhitelistUrl",
    "Refund",
    "Relationship",
    "RemoteSiteSetting",
    "Report",
    "ReportFolder",
    "ReportType",
    "RestrictionRule",
    "Role",
    "SamlSsoConfig",
    "Scontrol",
    "SearchSettings",
    "Security",
    "Service",
    "ServicePresence",
    "SessionSetting",
    "Settings",
    "Sharing",
    "SharingCriteriaRule",
    "SharingOwnerRule",
    "SharingReason",
    "SharingRecalculation",
    "SharingRule",
    "SharingRules",
    "SharingSet",
    "Site",
    "Skill",
    "Sku",
    "Solution",
    "StandardObject",
    "StaticResource",
    "Strike",
    "Subscription",
    "Survey",
    "SurveySubject",
    "SynonymDictionary",
    "System",
    "Tab",
    "TabSet",
    "Tax",
    "Territory",
    "Territory2",
    "Territory2Model",
    "Territory2Rule",
    "Test",
    "TimeSheet",
    "TimeSlot",
    "Timing",
    "Topic",
    "Tracking",
    "TransactionSecurityPolicy",
    "Translations",
    "Trigger",
    "UiPlugin",
    "User",
    "UserCriteria",
    "UserProvisioning",
    "ValidationRule",
    "WaveApplication",
    "WaveDashboard",
    "WaveDataflow",
    "WaveDataset",
    "WaveRecipe",
    "WebLink",
    "WebStore",
    "Workflow",
    "WorkflowAlert",
    "WorkflowFieldUpdate",
    "WorkflowFlowAction",
    "WorkflowKnowledgePublish",
    "WorkflowOutboundMessage",
    "WorkflowRule",
    "WorkflowSend",
    "WorkflowTask",
    "XOrgHub",
]
