apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sfir-ingress
  namespace: sfir
  labels:
    app.kubernetes.io/name: sfir-backend
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: sfir
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/limit-rps: "200"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.sfir.dev"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.sfir.dev
      secretName: sfir-api-tls
  rules:
    - host: api.sfir.dev
      http:
        paths:
          - path: /api/v1/ws
            pathType: Prefix
            backend:
              service:
                name: sfir-api
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sfir-api
                port:
                  number: 8000
